
data class Post(
    val id: Int,
    val ownerId: Int,
    val fromId: Int,
    val createdBy: Int,
    val date: Int,
    val text: String,
    val replyOwnerId: Int,
    val replyPostId: Int,
    val friendsOnly: Boolean,
    val comments: Comments,
    val copyRight: Copyright,
    val likes: Likes,
    val reposts: Reposts,
    val views: View,
    val postType: String,
    val signerId: Int,
    val postSource: PostSource?,
    val geo: Geo,
    val copyHistory: Array<Reposts>?,
    val donut: Donut,
    val canPin: Boolean = true,
    val canDelete: Boolean = true,
    val canEdit: Boolean = true,
    val isPinned: Boolean = false,
    val markedAsAds: Boolean = true,
    val isFavourite: Boolean = false,
    val postponedId: Int,
    val attachments: Array<Attachment>? = emptyArray()
)